version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: node-app-network
    networks:
      - my-network
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: react-app-network
    networks:
      - my-network
    ports:
      - "3000:3000"

networks:
  my-network:
